version: 2.1

orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: lasse1900/rails-example-project
          tag: "latest"

  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter

jobs:
  build:
    machine: true
    #docker:
    # image: lasse1900/docker-rails-example

    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |

            docker login --username=${DOCKER_LOGIN} --password=${DOCKER_PASSWORD}

            sudo curl https://cli-assets.heroku.com/install.sh | sh

            docker build -t rails-example-project .
            docker tag rails-example-project registry.heroku.com/rails-example-project/web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login

            docker push registry.heroku.com/rails-example-project/web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release web -a rails-example-project
